### ISSUE TITLE
Add support for `cancel`

### ISSUE THREAD

**Issue by pepijnve** [asciidoctor/asciimath#23]

**Comment by pepijnve** [comment]
@GarkGarcia seems like you'll need https://www.ctan.org/pkg/cancel to support this in LaTeX. Is that something you could have a look at integrating in the LaTeX backend?

**Comment by GarkGarcia** [comment]
> @GarkGarcia seems like you'll need https://www.ctan.org/pkg/cancel to support this in LaTeX. Is that something you could have a look at integrating in the LaTeX backend?

Actually, the way things were implemented, the `cancel` binary operator should now work in LaTeX without any changes to the code-base 😋️.

This is because when it encounters a symbol `s` which is not included in the `SYMBOLS` table, the LaTeX processor defaults to rendering it as `'\\#{s.to_s}'` (which is `'\\cancel'` in this case).

The only thing we'll have to do is updating the notes about the LaTeX output.

**Comment by GarkGarcia** [comment]
Also, we should update the specs too. I'll work on this things.

**Comment by GarkGarcia** [comment]
Fixed on https://github.com/asciidoctor/asciimath/commit/0d9aad240e4e24236b77d1c3d7d5159c4ff7c0ef.
