### ISSUE TITLE
LaTeX and mathml issues in parser_spec

### ISSUE THREAD

**Issue by davidfarmer** [asciidoctor/asciimath#25]
I only became aware of this project recently, so apologies if these comments are
premature.

In parser_spec.rb, which I assume you are using to test your parser,
there are some constructions which are not optimal.

z_12^34 should be z_{12}^{34} in latex.

Writing f\left( x \right) in latex does not look good.  If you compare that to f(x)
you will see that the version with the right and left has too much space after the "f".
(It seems tricky to decide when the object in parentheses is large,
so that the left and right are needed.  I'm interested to hear if you have
a way to deal with that.)

In mathml, mfenced is deprecated.  See https://developer.mozilla.org/en-US/docs/Web/MathML/Element/mfenced
But more importantly, in mathml you can (and should) distinguish between
function application and implied multiplication.  That can be done with the
function application character `&#x2061;`.  If your parser knows that f(x)
is "the function f at the argument x", then you can output it that way.

**Comment by pepijnve** [comment]
The LaTeX backend is very very new. @GarkGarcia finished the first version only yesterday. Any early feedback is definitely welcome.

I’ll have a look at `mfenced`. I didn’t realize this was deprecated. When I wrote the code initially it was based on MathML 2; can’t remember seeing that it was deprecated there. Not a big deal to change the backend to use some other construct.

Function application is a tricky one. The asciimath grammar doesn’t really provide a means to explicitly state something is a function. In other words, at the AST level we do not know something is a function, a variable, ...
This higher level interpretation gets handled by the backends. We could mark certain symbols as functions there and change the rendering accordingly or try to make this user configurable. That being said, for better or worse the current output is largely based on what asciimath.js generates. I’ve always been a bit reluctant to diverge from that implementation too much since this project is intended to serve as a kind of drop in replacement.

**Comment by GarkGarcia** [comment]
Hey, I'm the one responsible for the LaTeX processor.

> z_12^34 should be z_{12}^{34} in latex.

I see. This should be an easy fix, I'll work on it as soon as I can.

> It seems tricky to decide when the object in parentheses is large,
so that the left and right are needed. I'm interested to hear if you have
a way to deal with that.

We haven't found a way to deal with this. This is why `\left` and `\right` are necessary. Unless we find a way to algorithmically determine if an expression is "big", we'll have to use `\left` and `\right` for everything.

**Comment by davidfarmer** [comment]
I thought f and g are always functions in AsciiMath?

There are at least some cases where you don't need the left and right around
function arguments: one character, multiple characters with only +, -, and multiplication between them.  Not obvious to me if the default should
be to have left and right, or the default should be to no have those.

I understand that you are trying to replicate existing asciimath.  There are a lot of things I like about AsciiMath, but there are some design decisions which seem
like they may limit you.

**Comment by pepijnve** [comment]
> I thought f and g are always functions in AsciiMath?

They're described as such on the website and marked the same in the asciimath.js code, but I never quite understood what the intention of that was. AsciiMath.js smushes grammar parsing and MathML output into one step so it's not always easy to figure out what's going on. At the grammar level functions don't really exist, they match the `v` rule like other symbols.

The asciimath.js implementation does apply some [function hacks](https://github.com/asciimath/asciimathml/blame/master/ASCIIMathML.js#L702), but I don't really understand what's going on there. In terms of generated output I was never able to spot any differences. For instance `f x h x` get's converted to `<mi>f</mi><mi>x</mi><mi>h</mi><mi>x</mi>`. Even with parentheses present the rendering of `f(x)` and `h(x)` is identical.

I'm open to suggestions here if there's anything we should do differently in terms of MathML output.

**Comment by pepijnve** [comment]
Regarding `mfenced`, MDN is a bit overeager here. It is not deprecated in MathML 3, but will be in the next revision. I've logged issue #26 to track this and added some extra details there.

**Comment by pepijnve** [comment]
> but there are some design decisions which seem like they may limit you.

Just FYI, this implementation started as a workalike of asciimath.js with a very similar implementation. That means parsing the grammar and outputting MathML were kind of intermingled. As part of adding the LaTeX backend, @GarkGarcia and I worked on introducing a better defined AST that models http://asciimath.org/#grammar as close as possible.
I've tried to describe what's currently done at https://github.com/asciidoctor/asciimath/blob/master/AST.adoc This is the part that I'm reluctant to change since that defines the precedence of parsing.

What we could consider doing is adding support for a dialect of asciimath with different grammar rules. Not something I'm planning to work on myself, but I'm happy to accept PRs along those lines.

On the MathML output front we have a lot of flexibility now. I don't think it's a problem to make tweaks to that if something isn't being rendered correctly.

**Comment by GarkGarcia** [comment]
I believe this issue could be closed. I've created separate issues to track the progress on the improvements @davidfarmer proposed.

**Comment by davidfarmer** [comment]
> What we could consider doing is adding support for a dialect of asciimath with different grammar rules.
> Not something I'm planning to work on myself, but I'm happy to accept PRs along those lines.

I have a dormant project to specify and parse an asciimath-like
syntax that retains semantic information.  When it comes alive again,
I'll let you know.

**Comment by pepijnve** [comment]
@davidfarmer are you ok with closing this issue for now?

**Comment by davidfarmer** [comment]
I will close this issue, because the things I mentioned are now elsewhere.
(An apparent anomaly of GitHub is that you can close an issue you opened,
even if you have no authority over the repository.)
